global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
- job_name: redis_exporter
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_service_name
    regex: default;kubernetes
    action: drop
  - source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_container_port_number
    regex: default;9121
    action: keep
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
